#
# Copyright (c) 2020 INESC TEC <https://www.inesctec.pt>
#
# This Source Code Form is subject to the terms of the European Union
# Public License, v. 1.2. If a copy of the EUPL was not distributed with
# this file, You can obtain one at https://opensource.org/licenses/EUPL-1.2.
#
# SPDX-License-Identifier: EUPL-1.2
#

name: Android Check Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: '10'
      - uses: actions/setup-java@v1
        with:
            java-version: '1.8'
            java-package: jdk
            architecture: x64

      - uses: actions/cache@v2
        id: npm_cache
        name: Cache npm dependencies
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-npm-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install npm dependencies
        if: steps.npm_cache.outputs.cache-hit != 'true'
        run: yarn --ignore-scripts

      - name: Setup environment
        run: |
          wget https://github.com/google/exposure-notifications-android/raw/7dc2979051703443895123f83c370f64a81baa38/app/libs/play-services-nearby-18.0.3-eap.aar -P android/app/libs
          cp .env.example android/.env

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleProductionRelease \
            -PkeystoreFile="$GITHUB_WORKSPACE/android/app/debug.keystore" \
            -PkeystorePassword="android" \
            -PkeyAlias="androiddebugkey" \
            -PkeyPassword="android"
