#
# Copyright (c) 2020 INESC TEC <https://www.inesctec.pt>
#
# This Source Code Form is subject to the terms of the European Union
# Public License, v. 1.2. If a copy of the EUPL was not distributed with
# this file, You can obtain one at https://opensource.org/licenses/EUPL-1.2.
#
# SPDX-License-Identifier: EUPL-1.2
#

name: Android Check Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        name: Cache npm dependencies
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: |
          yarn --ignore-scripts
          yarn postinstall_android

      - name: Setup environment
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570"
          cp .env.example android/.env

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleProductionRelease \
            -PkeystoreFile="$GITHUB_WORKSPACE/android/app/debug.keystore" \
            -PkeystorePassword="android" \
            -PkeyAlias="androiddebugkey" \
            -PkeyPassword="android"
