#
# Copyright (c) 2020 INESC TEC <https://www.inesctec.pt>
#
# This Source Code Form is subject to the terms of the European Union
# Public License, v. 1.2. If a copy of the EUPL was not distributed with
# this file, You can obtain one at https://opensource.org/licenses/EUPL-1.2.
#
# SPDX-License-Identifier: EUPL-1.2
#

name: Android Production Staging Build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        name: Cache npm dependencies
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install npm dependencies
        run: |
          yarn --ignore-scripts
          yarn postinstall_android

      - name: Setup environment
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570"
          echo "${{secrets.ENV_PRODUCTION_STAGING}}" > android/.env

      - name: Build ABB
        run: |
          cd android
          ./gradlew bundleProductionStaging

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleProductionStaging

      - name: Upload AAB
        uses: actions/upload-artifact@v2
        with:
          name: app-production-staging.aab
          path: android/app/build/outputs/bundle/productionStaging/app-production-staging.aab

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-production-staging.apk
          path: android/app/build/outputs/apk/production/staging/app-production-staging.apk

      - name: Upload Mapping File
        uses: actions/upload-artifact@v2
        with:
          name: mapping.text
          path: android/app/build/outputs/mapping/productionStaging/mapping.txt

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download APK artifcat
        uses: actions/download-artifact@v2
        with:
          name: app-production-staging.apk

      - name: Upload artifact to App Center
        uses: wzieba/AppCenter-Github-Action@v1.1.1
        with:
          appName: ${{secrets.APPCENTER_ORG}}/${{secrets.APPCENTER_APP_PRODUCTION_STAGING}}
          token: ${{secrets.APPCENTER_TOKEN_PRODUCTION_STAGING}}
          group: Internal
          file: app-production-staging.apk
