#
# Copyright (c) 2020 INESC TEC <https://www.inesctec.pt>
#
# This Source Code Form is subject to the terms of the European Union
# Public License, v. 1.2. If a copy of the EUPL was not distributed with
# this file, You can obtain one at https://opensource.org/licenses/EUPL-1.2.
#
# SPDX-License-Identifier: EUPL-1.2
#

name: iOS Check Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CI: true

jobs:
  build:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: '10'

      - name: Get node cache directory path
        id: pods-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: node-cache
        name: Cache node dependencies
        with:
          path: ${{ steps.pods-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-

      - uses: actions/cache@v2
        id: pods-cache
        name: Cache pods dependencies
        with:
          path: 'ios/Pods'
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: ${{ runner.os }}-pods-

      - name: Install node dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn --ignore-scripts

      - name: Install pods dependencies
        if: steps.pods-cache.outputs.cache-hit != 'true'
        run: (cd ios && pod install)

      - name: Switch to Xcode 11.6
        run: sudo xcode-select --switch /Applications/Xcode_11.6.app

      - name: Setup environment
        run: |
          cp .env.example .env.production.release

      - name: Build IPA
        run: |
          cd ios
          xcodebuild build -workspace Divoc.xcworkspace -configuration=ProductionRelease -scheme Divoc.production.release -destination platform="iOS Simulator,name=iPhone 11 Pro Max"
